export let AppStatus = {
    BEFORE_BOOTSTRAP : 'BEFORE_BOOTSTRAP',
    BOOTSTRAPPED : 'BOOTSTRAPPED',
    BEFORE_MOUNT : 'BEFORE_MOUNT',
    MOUNTED : 'MOUNTED',
    BEFORE_UNMOUNT : 'BEFORE_UNMOUNT',
    UNMOUNTED : 'UNMOUNTED',
    BOOTSTRAP_ERROR : 'BOOTSTRAP_ERROR',
    MOUNT_ERROR : 'MOUNT_ERROR',
    UNMOUNT_ERROR : 'UNMOUNT_ERROR',
}